### ISSUE TITLE
Truncated documentation

### ISSUE THREAD

**Issue by luyoutao** [Kraus-Lab/groHMM#3]
Dear authors, 

Thanks for developing the package. In the documentation, it is common to see truncated sentences, such as 

```
LtProbA
    Log probability of t... . Default: -5. One of these is just an initialization, and the final value is set by EM. The other is a holdout parameter.
LtProbB
    Log probability of t... . Default: -200.
size
    Log probability of t... . Default: -5.
```

This will cause confusion to users.

**Comment by anaga2** [comment]
Thanks @foehnwind . The only correction that had to be made was to the description of the argument 'size'. It has been updated now. The ... section in the description are not truncated sentences but extra arguments as listed at the bottom of the argument section of the manual.

**Comment by luyoutao** [comment]
Thanks @anaga2. But I still don't understand what "Log probability of t..." mean. This sentence seems incomplete.
